# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: search_cluster_protos.proto
"""Generated protocol buffer code."""
from google.protobuf.internal import builder as _builder
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import symbol_database as _symbol_database
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\x1bsearch_cluster_protos.proto\x12\x12\x64istributed.search\"\x1f\n\x07Request\x12\x14\n\x0csearch_query\x18\x01 \x02(\t\"\xb0\x01\n\x08Response\x12\x46\n\x12relevant_documents\x18\x01 \x03(\x0b\x32*.distributed.search.Response.DocumentStats\x1a\\\n\rDocumentStats\x12\x15\n\rdocument_name\x18\x01 \x02(\t\x12\r\n\x05score\x18\x02 \x01(\x01\x12\x15\n\rdocument_size\x18\x03 \x01(\x03\x12\x0e\n\x06\x61uthor\x18\x04 \x01(\tB\x1a\n\x0bmodel.protoB\x0bSearchModel')

_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, globals())
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'search_cluster_protos_pb2', globals())
if _descriptor._USE_C_DESCRIPTORS == False:

  DESCRIPTOR._options = None
  DESCRIPTOR._serialized_options = b'\n\013model.protoB\013SearchModel'
  _REQUEST._serialized_start=51
  _REQUEST._serialized_end=82
  _RESPONSE._serialized_start=85
  _RESPONSE._serialized_end=261
  _RESPONSE_DOCUMENTSTATS._serialized_start=169
  _RESPONSE_DOCUMENTSTATS._serialized_end=261
# @@protoc_insertion_point(module_scope)
